# ConfigMap with definition of Grafana data source.
# Data Source have YAML format.
# Label grafana_datasource is mandatory to detect this ConfigMap by Grafana helm chart.

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: default
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
      # <string, required> name of the datasource. Required
    - name: prometheus
      # <string, required> datasource type. Required
      type: prometheus
      # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> url
      url: http://prometheus-server
      # <string> database password, if used
      password:
      # <string> database user, if used
      user:
      # <string> database name, if used
      database:
      # <bool> enable/disable basic auth
      basicAuth:
      # <string> basic auth username
      basicAuthUser:
      # <string> basic auth password
      basicAuthPassword:
      # <bool> enable/disable with credentials headers
      withCredentials:
      # <bool> mark as default datasource. Max one per org
      isDefault:
      # <string> json object of data that will be encrypted.
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: true
