apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-example
  namespace: kubernetes-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node-example
        image: vamin2/node-example
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: node-example
  namespace: kubernetes-demo
  labels:
    app: node-example
spec:
  selector:
    app: node-example
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30010
  type: NodePort
---
