apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-example
  namespace: szkolenie
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: node-example
  targetCPUUtilizationPercentage: 1
