kind: Service
apiVersion: v1
metadata:
  name: nginx-kubernetes-demo
  namespace: kubernetes-demo
spec:
  selector:
    app: nginx-kubernetes-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80