apiVersion: v1
kind: Pod
metadata:
  namespace: kubernetes-demo
  name: nginx
  labels:
    env: test
    app: nginx-kubernetes-demo
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
