---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod-nginx
  #name: task-pv-pod-apache
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: myclaim
  containers:
    - name: task-pv-container
      image: nginx
      #image: httpd
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
        #- mountPath: "/var/www/html"
          name: task-pv-storage
      resources: {}